removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
player forceAddUniform "GSRI_shirt_green";
player addItemToUniform "ACE_Flashlight_XL50";
player addItemToUniform "ACE_WaterBottle";
player addItemToUniform "ACE_WaterBottle";
player addHeadgear "GSRI_beret";
player linkItem "ItemMap";
player linkItem "ItemWatch";
["GSRI_locker_getPreslot", [localize "STR_GSRI_locker_gearAsRegular"]] call BIS_fnc_showNotification;
