removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this addWeapon "LMG_03_F";
this addPrimaryWeaponItem "muzzle_snds_H_MG_blk_F";
this addPrimaryWeaponItem "optic_MRCO";
this addPrimaryWeaponItem "200Rnd_556x45_Box_F";
this forceAddUniform "GSRI_uniform";
this addVest "GSRI_vest_carrier_lite";
this addBackpack "GSRI_AssaultPack";
for "_i" from 1 to 10 do {this addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 4 do {this addItemToUniform "ACE_splint";};
for "_i" from 1 to 4 do {this addItemToUniform "ACE_tourniquet";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_CableTie";};
this addItemToUniform "A3_GPNVG18_F";
for "_i" from 1 to 2 do {this addItemToVest "ACE_MRE_LambCurry";};
for "_i" from 1 to 3 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "ACE_M84";};
this addItemToVest "200Rnd_556x45_Box_F";
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_WaterBottle";};
for "_i" from 1 to 3 do {this addItemToBackpack "200Rnd_556x45_Box_F";};
this addHeadgear "GSRI_helmet_modular";
this addGoggles "GSRI_balaclava_v2_camo";
this linkItem "ItemWatch";
this linkItem "TFAR_anprc152";
["GSRI_locker_getPreslot", [localize "STR_GSRI_locker_gearAsTad"]] call BIS_fnc_showNotification;
