removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
player addWeapon "LMG_03_F";
player addPrimaryWeaponItem "muzzle_snds_H_MG_blk_F";
player addPrimaryWeaponItem "optic_MRCO";
player addPrimaryWeaponItem "200Rnd_556x45_Box_F";
player forceAddUniform "GSRI_uniform";
player addVest "GSRI_vest_carrier_lite";
player addBackpack "GSRI_Kitbag";
for "_i" from 1 to 10 do {player addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 4 do {player addItemToUniform "ACE_splint";};
for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 4 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "A3_GPNVG18_F";
for "_i" from 1 to 2 do {player addItemToVest "ACE_MRE_LambCurry";};
for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {player addItemToVest "ACE_M84";};
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_WaterBottle";};
for "_i" from 1 to 4 do {player addItemToBackpack "200Rnd_556x45_Box_F";};
player addItemToBackpack "ACE_SpareBarrel";
player addHeadgear "GSRI_helmet_modular";
player addGoggles "GSRI_balaclava_v2_camo";
player linkItem "ItemWatch";
player linkItem "TFAR_anprc152";
["GSRI_locker_getPreslot", [localize "STR_GSRI_locker_gearAsTad"]] call BIS_fnc_showNotification;
