name: merge

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout files
      uses: actions/checkout@v4

    - name: Lint sources
      uses: jokoho48/sqflint@master
      with:
        args: --exit e --directory addons
